name: vtki-environment
channels:
  - bokeh/label/dev
dependencies:
  - python
  - bokeh
  - pip:
    - git+git://github.com/vtkiorg/vtki@master
    - matplotlib
    - git+git://github.com/pyviz/panel@v0.5.0
