#!/bin/bash
export PYVISTA_VIRTUAL_DISPLAY=True
export PYVISTA_OFF_SCREEN=true
export PYVISTA_USE_PANEL=true
export PYVISTA_PLOT_THEME=document
# This is needed for Panel - use with cuation!
export PYVISTA_AUTO_CLOSE=false
exec "$@"
