name: ci
on:
  pull_request:
  push:
    branches:
      - master
  schedule:
    - cron: "0 0 1 * *"  # once a month on main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: Install Python packages
        run: |
          pip install --upgrade pip
          pip install cookiecutter
      - name: Create from cookiecutter
        run: |
          cookiecutter --no-input . "github_account=test" "author_name=Test" "year=2022"
